version: "2"
run:
  timeout: 3m
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
  exclusions:
    generated: lax
    rules:
      - path: pkg/client/generated/generate.go
        linters:
          - revive
        text: "package-comments:"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
