#!/usr/bin/env bash
# Generate the complete documentation screenshot set from disposable data.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
output_dir="$repo_root/docs/assets/screenshots"

# shellcheck source-path=SCRIPTDIR
# shellcheck source=assets.sh
. "$script_dir/assets.sh"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--out DIR]

Generate the complete TUI and Web UI documentation screenshot set into DIR.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -ge 2 ]] || { printf 'ERROR: --out requires a directory\n' >&2; exit 2; }
      output_dir="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$output_dir")"
output_parent="$(cd "$(dirname "$output_dir")" && pwd -P)"
output_dir="$output_parent/$(basename "$output_dir")"

case "$output_dir" in
  ""|/|"$repo_root"|"$repo_root/docs"|"$repo_root/docs/assets")
    printf 'refusing unsafe docs screenshot output directory: %s\n' "$output_dir" >&2
    exit 1
    ;;
esac

rm -rf "$output_dir"
mkdir -p "$output_dir"
"$script_dir/generate-federation-tui.sh" --out "$output_dir"
"$script_dir/generate-web-ui.sh" --out "$output_dir"

cat >"$output_dir/README.md" <<'EOF'
# kata docs assets

This branch is generated by `docs/screenshots/update-assets-branch.sh` from
disposable synthetic Kata daemons and browser sessions.
EOF

cat >"$output_dir/manifest.json" <<'EOF'
{
  "generator": "docs/screenshots/generate.sh",
  "source": "disposable synthetic daemons and browser sessions",
  "screenshots": [
    "tui/hero.svg",
    "federation-tui/list.svg",
    "federation-tui/select-hub.svg",
    "federation-tui/select-hub-project.svg",
    "federation-tui/preview.svg",
    "federation-tui/result.svg",
    "web-ui/workspace.png",
    "web-ui/issue-detail.png",
    "web-ui/relationships.png",
    "web-ui/daemon-switcher.png"
  ]
}
EOF

kata_docs_validate_assets "$output_dir"
printf 'Generated documentation screenshots in %s\n' "$output_dir"
