#!/usr/bin/env bash
# Generate the complete documentation screenshot set from disposable data.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
default_output_dir="$repo_root/docs/assets/screenshots"
output_dir="$default_output_dir"

# shellcheck source-path=SCRIPTDIR
# shellcheck source=assets.sh
. "$script_dir/assets.sh"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--out DIR]

Generate the complete TUI and Web UI documentation screenshot set into DIR.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -ge 2 ]] || { printf 'ERROR: --out requires a directory\n' >&2; exit 2; }
      if [[ -z "$2" ]]; then
        printf 'refusing unsafe docs screenshot output directory: empty path\n' >&2
        exit 1
      fi
      output_dir="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -L "$output_dir" ]]; then
  printf 'refusing unsafe docs screenshot output directory symlink: %s\n' "$output_dir" >&2
  exit 1
fi
if [[ -e "$output_dir" && ! -d "$output_dir" ]]; then
  printf 'refusing unsafe docs screenshot output directory that is not a directory: %s\n' "$output_dir" >&2
  exit 1
fi

if [[ -d "$output_dir" ]]; then
  output_dir="$(cd "$output_dir" && pwd -P)"
else
  output_name="$(basename "$output_dir")"
  case "$output_name" in
    ""|.|..)
      printf 'refusing unsafe docs screenshot output directory: %s\n' "$output_dir" >&2
      exit 1
      ;;
  esac
  mkdir -p "$(dirname "$output_dir")"
  output_parent="$(cd "$(dirname "$output_dir")" && pwd -P)"
  output_dir="${output_parent%/}/$output_name"
fi

mkdir -p "$(dirname "$default_output_dir")"
default_output_parent="$(cd "$(dirname "$default_output_dir")" && pwd -P)"
default_output_dir="${default_output_parent%/}/$(basename "$default_output_dir")"

case "$output_dir" in
  ""|/|"$repo_root"|"$repo_root/docs"|"$repo_root/docs/assets")
    printf 'refusing unsafe docs screenshot output directory: %s\n' "$output_dir" >&2
    exit 1
    ;;
esac

if [[ -d "$output_dir" && "$output_dir" != "$default_output_dir" ]]; then
  if [[ -L "$output_dir/README.md" ]] ||
     [[ "$(head -n 1 "$output_dir/README.md" 2>/dev/null || true)" != "# kata docs assets" ]] ||
     ! kata_docs_validate_assets "$output_dir" >/dev/null 2>&1; then
    printf 'refusing to replace unowned docs screenshot directory: %s\n' "$output_dir" >&2
    exit 1
  fi
fi

output_parent="$(dirname "$output_dir")"
staging_dir="$(mktemp -d "$output_parent/.kata-docs-screenshots.XXXXXX")"
backup_dir=""
installed=false

remove_generator_temp_dir() {
  local path="$1"
  [[ -n "$path" ]] || return 0
  case "$path" in
    "$output_parent"/.kata-docs-screenshots.*|"$output_parent"/.kata-docs-screenshots-backup.*)
      rm -rf -- "$path"
      ;;
    *)
      printf 'refusing unsafe docs screenshot temporary directory cleanup: %s\n' "$path" >&2
      return 1
      ;;
  esac
}

cleanup() {
  remove_generator_temp_dir "$staging_dir"
  if [[ -n "$backup_dir" && -d "$backup_dir" ]]; then
    if [[ "$installed" == true ]]; then
      remove_generator_temp_dir "$backup_dir"
    elif [[ ! -e "$output_dir" ]]; then
      mv "$backup_dir" "$output_dir"
    else
      printf 'preserving previous docs screenshots after failed replacement: %s\n' "$backup_dir" >&2
    fi
  fi
}
trap cleanup EXIT
trap 'exit 1' HUP INT TERM

"$script_dir/generate-federation-tui.sh" --out "$staging_dir"
"$script_dir/generate-web-ui.sh" --out "$staging_dir"

cat >"$staging_dir/README.md" <<'EOF'
# kata docs assets

This branch is generated by `docs/screenshots/update-assets-branch.sh` from
disposable synthetic Kata daemons and browser sessions.
EOF

cat >"$staging_dir/manifest.json" <<'EOF'
{
  "generator": "docs/screenshots/generate.sh",
  "source": "disposable synthetic daemons and browser sessions",
  "screenshots": [
    "tui/hero.svg",
    "federation-tui/list.svg",
    "federation-tui/select-hub.svg",
    "federation-tui/select-hub-project.svg",
    "federation-tui/preview.svg",
    "federation-tui/result.svg",
    "web-ui/workspace.png",
    "web-ui/issue-detail.png",
    "web-ui/relationships.png",
    "web-ui/daemon-switcher.png"
  ]
}
EOF

kata_docs_validate_assets "$staging_dir"

if [[ -d "$output_dir" ]]; then
  backup_dir="$(mktemp -d "$output_parent/.kata-docs-screenshots-backup.XXXXXX")"
  rmdir "$backup_dir"
  mv "$output_dir" "$backup_dir"
fi
if ! mv "$staging_dir" "$output_dir"; then
  if [[ -n "$backup_dir" && ! -e "$output_dir" ]]; then
    mv "$backup_dir" "$output_dir"
    backup_dir=""
  fi
  exit 1
fi
staging_dir=""
installed=true
remove_generator_temp_dir "$backup_dir"
backup_dir=""
trap - EXIT HUP INT TERM

printf 'Generated documentation screenshots in %s\n' "$output_dir"
