// Code generated by ./stubgen; DO NOT EDIT.
//
// This file is regenerated from internal/db/storage.go's Storage interface
// each time //go:generate runs. To regenerate after changing the interface
// or implementing a method elsewhere in this package:
//
//	go generate ./internal/db/pgstore
//
// or, from this directory:
//
//	go run ./stubgen
//
// Methods implemented in store.go, open.go, or inherited from the
// embedded *sql.DB are skipped via stubgen/main.go's alreadyImplemented
// allow-list. The checked-in file has no stubs at full parity. When Storage
// grows, complete the new backend method by:
//
//  1. Adding the method name to alreadyImplemented in stubgen/main.go,
//  2. Writing the real implementation in a new pgstore .go file, and
//  3. Re-running go generate so this file no longer carries the stub.

package pgstore

import (
	"go.kenn.io/kata/internal/db"
)

// Compile-time check that *Store satisfies db.Storage. The assertion stays
// here so a missing or mistyped method is caught at build time; the inventory
// test separately requires every method to have shared conformance coverage.
var _ db.Storage = (*Store)(nil)
