import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

import { generate } from 'orval'

const webDirectory = fileURLToPath(new URL('..', import.meta.url))
const schema = fileURLToPath(new URL('../../api/openapi.yaml', import.meta.url))
const output = fileURLToPath(new URL('../src/lib/api/generated', import.meta.url))
const mutator = fileURLToPath(new URL('../src/lib/api/client.ts', import.meta.url))
const prettierConfig = fileURLToPath(new URL('../.prettierrc.json', import.meta.url))
const check = process.argv.includes('--check')
const temporaryDirectory = check
  ? await mkdtemp(join(dirname(output), '.generated-check-'))
  : undefined
const destination = temporaryDirectory ?? output

async function generatedSources(
  directory: string,
  base = directory,
  sources = new Map<string, string>(),
): Promise<Map<string, string>> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) {
      await generatedSources(path, base, sources)
    } else if (entry.name.endsWith('.ts')) {
      sources.set(relative(base, path), await readFile(path, 'utf8'))
    }
  }
  return sources
}

async function writeIndex(): Promise<void> {
  const exports = ["export * from './models'"]
  for (const entry of await readdir(destination, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'models') continue
    exports.push(`export * from './${entry.name}/${entry.name}'`)
  }
  await writeFile(join(destination, 'index.ts'), `${exports.sort().join('\n')}\n`)
}

try {
  await mkdir(dirname(destination), { recursive: true })
  await generate(
    {
      input: {
        target: schema,
        override: {
          transformer: (document) => {
            if (document.paths) delete document.paths['/api/v1/events/stream']
            return document
          },
        },
      },
      output: {
        client: 'fetch',
        mode: 'tags-split',
        target: destination,
        schemas: join(destination, 'models'),
        clean: true,
        urlEncodeParameters: true,
        override: {
          fetch: { includeHttpResponseReturnType: true },
          header: () => ['Generated by Orval. Do not edit manually.'],
          mutator: { path: mutator, name: 'orvalFetch' },
          useNamedParameters: true,
        },
      },
    },
    webDirectory,
  )
  await writeIndex()

  const formatted = Bun.spawnSync([
    process.execPath,
    'x',
    'prettier',
    '--config',
    prettierConfig,
    '--write',
    destination,
  ])
  if (!formatted.success) {
    process.stderr.write(formatted.stderr)
    process.exit(formatted.exitCode)
  }

  if (check) {
    const [expected, actual] = await Promise.all([
      generatedSources(output),
      generatedSources(destination),
    ])
    const paths = new Set([...expected.keys(), ...actual.keys()])
    const changed = [...paths].filter((path) => expected.get(path) !== actual.get(path))
    if (changed.length > 0) {
      console.error(
        `generated browser API client is stale; run \`bun run generate\`:\n${changed.join('\n')}`,
      )
      process.exit(1)
    }
  }
} finally {
  if (temporaryDirectory) {
    await rm(temporaryDirectory, { recursive: true, force: true })
  }
}
