// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions is the options needed to make a request to TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet.
type TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions struct {
	Query *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions is the options needed to make a request to ReopenTaskAPIV1TasksTaskIDReopenPost.
type ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions struct {
	PathParams *ReopenTaskAPIV1TasksTaskIDReopenPostPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// CloseTaskAPIV1TasksTaskIDClosePostRequestOptions is the options needed to make a request to CloseTaskAPIV1TasksTaskIDClosePost.
type CloseTaskAPIV1TasksTaskIDClosePostRequestOptions struct {
	PathParams *CloseTaskAPIV1TasksTaskIDClosePostPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetProjectAPIV1ProjectsProjectIDGetRequestOptions is the options needed to make a request to GetProjectAPIV1ProjectsProjectIDGet.
type GetProjectAPIV1ProjectsProjectIDGetRequestOptions struct {
	PathParams *GetProjectAPIV1ProjectsProjectIDGetPath
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetProjectAPIV1ProjectsProjectIDGetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetProjectAPIV1ProjectsProjectIDGetRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetProjectAPIV1ProjectsProjectIDGetRequestOptions) GetQuery() (map[string]any, error) {
	return nil, nil
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetProjectAPIV1ProjectsProjectIDGetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetProjectAPIV1ProjectsProjectIDGetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetSectionAPIV1SectionsSectionIDGetRequestOptions is the options needed to make a request to GetSectionAPIV1SectionsSectionIDGet.
type GetSectionAPIV1SectionsSectionIDGetRequestOptions struct {
	PathParams *GetSectionAPIV1SectionsSectionIDGetPath
	Query      *GetSectionAPIV1SectionsSectionIDGetQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetSectionAPIV1SectionsSectionIDGetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetSectionAPIV1SectionsSectionIDGetRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetSectionAPIV1SectionsSectionIDGetRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetSectionAPIV1SectionsSectionIDGetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetSectionAPIV1SectionsSectionIDGetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetTaskAPIV1TasksTaskIDGetRequestOptions is the options needed to make a request to GetTaskAPIV1TasksTaskIDGet.
type GetTaskAPIV1TasksTaskIDGetRequestOptions struct {
	PathParams *GetTaskAPIV1TasksTaskIDGetPath
	Query      *GetTaskAPIV1TasksTaskIDGetQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetTaskAPIV1TasksTaskIDGetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetTaskAPIV1TasksTaskIDGetRequestOptions) GetPathParams() (map[string]any, error) {
	return runtime.AsMap[any](o.PathParams)
}

// GetQuery returns the query params as a map.
func (o *GetTaskAPIV1TasksTaskIDGetRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetTaskAPIV1TasksTaskIDGetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetTaskAPIV1TasksTaskIDGetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}

// GetTasksAPIV1TasksGetRequestOptions is the options needed to make a request to GetTasksAPIV1TasksGet.
type GetTasksAPIV1TasksGetRequestOptions struct {
	Query *GetTasksAPIV1TasksGetQuery
}

// Validate validates all the fields in the options.
// Use it if fields validation was not run.
func (o *GetTasksAPIV1TasksGetRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// GetPathParams returns the path params as a map.
func (o *GetTasksAPIV1TasksGetRequestOptions) GetPathParams() (map[string]any, error) {
	return nil, nil
}

// GetQuery returns the query params as a map.
func (o *GetTasksAPIV1TasksGetRequestOptions) GetQuery() (map[string]any, error) {
	return runtime.AsMap[any](o.Query)
}

// GetBody returns the payload in any type that can be marshalled to JSON by the client.
func (o *GetTasksAPIV1TasksGetRequestOptions) GetBody() any {
	return nil
}

// GetHeader returns the headers as a map.
func (o *GetTasksAPIV1TasksGetRequestOptions) GetHeader() (map[string]string, error) {
	return nil, nil
}
