// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet Tasks Completed By Completion Date
func (c *Client) TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetWithResponse(ctx context.Context, options *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/completed/by_completion_date",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/completed/by_completion_date")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// ReopenTaskAPIV1TasksTaskIDReopenPost Reopen Task
func (c *Client) ReopenTaskAPIV1TasksTaskIDReopenPostWithResponse(ctx context.Context, options *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ReopenTaskAPIV1TasksTaskIDReopenPostResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}/reopen",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}/reopen")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &ReopenTaskAPIV1TasksTaskIDReopenPostResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(ReopenTaskAPIV1TasksTaskIDReopenPostResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "ReopenTaskAPIV1TasksTaskIDReopenPostResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// CloseTaskAPIV1TasksTaskIDClosePost Close Task
func (c *Client) CloseTaskAPIV1TasksTaskIDClosePostWithResponse(ctx context.Context, options *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloseTaskAPIV1TasksTaskIDClosePostResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}/close",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}/close")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &CloseTaskAPIV1TasksTaskIDClosePostResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(CloseTaskAPIV1TasksTaskIDClosePostResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "CloseTaskAPIV1TasksTaskIDClosePostResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetProjectAPIV1ProjectsProjectIDGet Get Project
func (c *Client) GetProjectAPIV1ProjectsProjectIDGetWithResponse(ctx context.Context, options *GetProjectAPIV1ProjectsProjectIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetProjectAPIV1ProjectsProjectIDGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/projects/{project_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/projects/{project_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetProjectAPIV1ProjectsProjectIDGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetProjectAPIV1ProjectsProjectIDGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetProjectAPIV1ProjectsProjectIDGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetSectionAPIV1SectionsSectionIDGet Get Section
func (c *Client) GetSectionAPIV1SectionsSectionIDGetWithResponse(ctx context.Context, options *GetSectionAPIV1SectionsSectionIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetSectionAPIV1SectionsSectionIDGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/sections/{section_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/sections/{section_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetSectionAPIV1SectionsSectionIDGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetSectionAPIV1SectionsSectionIDGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetSectionAPIV1SectionsSectionIDGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetTaskAPIV1TasksTaskIDGet Get Task
func (c *Client) GetTaskAPIV1TasksTaskIDGetWithResponse(ctx context.Context, options *GetTaskAPIV1TasksTaskIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTaskAPIV1TasksTaskIDGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetTaskAPIV1TasksTaskIDGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetTaskAPIV1TasksTaskIDGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetTaskAPIV1TasksTaskIDGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// GetTasksAPIV1TasksGet Get Tasks
func (c *Client) GetTasksAPIV1TasksGetWithResponse(ctx context.Context, options *GetTasksAPIV1TasksGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTasksAPIV1TasksGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &GetTasksAPIV1TasksGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(GetTasksAPIV1TasksGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "GetTasksAPIV1TasksGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}

// UserInfoAPIV1UserGet User Info
func (c *Client) UserInfoAPIV1UserGetWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*UserInfoAPIV1UserGetResp, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/user",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/user")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}

	out := &UserInfoAPIV1UserGetResp{
		HTTPResponse: resp.Raw,
		Body:         resp.Content,
		StatusCode:   resp.StatusCode,
	}

	switch resp.StatusCode {
	case 200:
		out.JSON200 = new(UserInfoAPIV1UserGetResponse)
		bodyBytes := resp.Content
		if len(bodyBytes) > 0 {
			if err := json.Unmarshal(bodyBytes, out.JSON200); err != nil {
				return out, &runtime.ResponseDecodeError{
					StatusCode:    resp.StatusCode,
					ContentType:   resp.Headers.Get("Content-Type"),
					ContentLength: len(bodyBytes),
					TargetType:    "UserInfoAPIV1UserGetResponse",
					Body:          bodyBytes,
					Err:           err,
				}
			}
		}
		return out, nil
	default:
		return out, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode), runtime.WithStatusCode(resp.StatusCode))
	}
}
