// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// Client is the client for the API implementing the Client interface.
type Client struct {
	apiClient runtime.APIClient
}

// NewClient creates a new instance of the Client client.
func NewClient(apiClient runtime.APIClient) *Client {
	return &Client{apiClient: apiClient}
}

// NewDefaultClient creates a new instance of the Client client with default api client.
func NewDefaultClient(baseURL string, opts ...runtime.APIClientOption) (*Client, error) {
	apiClient, err := runtime.NewAPIClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("error creating API client: %w", err)
	}
	return &Client{apiClient: apiClient}, nil
}

// ClientInterface is the interface for the API client.
type ClientInterface interface {
	// TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet Tasks Completed By Completion Date
	TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet(ctx context.Context, options *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse, error)
	TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetWithResponse(ctx context.Context, options *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResp, error)

	// ReopenTaskAPIV1TasksTaskIDReopenPost Reopen Task
	ReopenTaskAPIV1TasksTaskIDReopenPost(ctx context.Context, options *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ReopenTaskAPIV1TasksTaskIDReopenPostResponse, error)
	ReopenTaskAPIV1TasksTaskIDReopenPostWithResponse(ctx context.Context, options *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ReopenTaskAPIV1TasksTaskIDReopenPostResp, error)

	// CloseTaskAPIV1TasksTaskIDClosePost Close Task
	CloseTaskAPIV1TasksTaskIDClosePost(ctx context.Context, options *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloseTaskAPIV1TasksTaskIDClosePostResponse, error)
	CloseTaskAPIV1TasksTaskIDClosePostWithResponse(ctx context.Context, options *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloseTaskAPIV1TasksTaskIDClosePostResp, error)

	// GetProjectAPIV1ProjectsProjectIDGet Get Project
	GetProjectAPIV1ProjectsProjectIDGet(ctx context.Context, options *GetProjectAPIV1ProjectsProjectIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetProjectAPIV1ProjectsProjectIDGetResponse, error)
	GetProjectAPIV1ProjectsProjectIDGetWithResponse(ctx context.Context, options *GetProjectAPIV1ProjectsProjectIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetProjectAPIV1ProjectsProjectIDGetResp, error)

	// GetSectionAPIV1SectionsSectionIDGet Get Section
	GetSectionAPIV1SectionsSectionIDGet(ctx context.Context, options *GetSectionAPIV1SectionsSectionIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetSectionAPIV1SectionsSectionIDGetResponse, error)
	GetSectionAPIV1SectionsSectionIDGetWithResponse(ctx context.Context, options *GetSectionAPIV1SectionsSectionIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetSectionAPIV1SectionsSectionIDGetResp, error)

	// GetTaskAPIV1TasksTaskIDGet Get Task
	GetTaskAPIV1TasksTaskIDGet(ctx context.Context, options *GetTaskAPIV1TasksTaskIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTaskAPIV1TasksTaskIDGetResponse, error)
	GetTaskAPIV1TasksTaskIDGetWithResponse(ctx context.Context, options *GetTaskAPIV1TasksTaskIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTaskAPIV1TasksTaskIDGetResp, error)

	// GetTasksAPIV1TasksGet Get Tasks
	GetTasksAPIV1TasksGet(ctx context.Context, options *GetTasksAPIV1TasksGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTasksAPIV1TasksGetResponse, error)
	GetTasksAPIV1TasksGetWithResponse(ctx context.Context, options *GetTasksAPIV1TasksGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTasksAPIV1TasksGetResp, error)

	// UserInfoAPIV1UserGet User Info
	UserInfoAPIV1UserGet(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*UserInfoAPIV1UserGetResponse, error)
	UserInfoAPIV1UserGetWithResponse(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*UserInfoAPIV1UserGetResp, error)
}

// TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet Tasks Completed By Completion Date
func (c *Client) TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGet(ctx context.Context, options *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/completed/by_completion_date",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/completed/by_completion_date")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// ReopenTaskAPIV1TasksTaskIDReopenPost Reopen Task
func (c *Client) ReopenTaskAPIV1TasksTaskIDReopenPost(ctx context.Context, options *ReopenTaskAPIV1TasksTaskIDReopenPostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*ReopenTaskAPIV1TasksTaskIDReopenPostResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}/reopen",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*ReopenTaskAPIV1TasksTaskIDReopenPostResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(ReopenTaskAPIV1TasksTaskIDReopenPostResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "ReopenTaskAPIV1TasksTaskIDReopenPostResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}/reopen")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// CloseTaskAPIV1TasksTaskIDClosePost Close Task
func (c *Client) CloseTaskAPIV1TasksTaskIDClosePost(ctx context.Context, options *CloseTaskAPIV1TasksTaskIDClosePostRequestOptions, reqEditors ...runtime.RequestEditorFn) (*CloseTaskAPIV1TasksTaskIDClosePostResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}/close",
		Method:     "POST",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*CloseTaskAPIV1TasksTaskIDClosePostResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(CloseTaskAPIV1TasksTaskIDClosePostResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "CloseTaskAPIV1TasksTaskIDClosePostResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}/close")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetProjectAPIV1ProjectsProjectIDGet Get Project
func (c *Client) GetProjectAPIV1ProjectsProjectIDGet(ctx context.Context, options *GetProjectAPIV1ProjectsProjectIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetProjectAPIV1ProjectsProjectIDGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/projects/{project_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetProjectAPIV1ProjectsProjectIDGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetProjectAPIV1ProjectsProjectIDGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetProjectAPIV1ProjectsProjectIDGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/projects/{project_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetSectionAPIV1SectionsSectionIDGet Get Section
func (c *Client) GetSectionAPIV1SectionsSectionIDGet(ctx context.Context, options *GetSectionAPIV1SectionsSectionIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetSectionAPIV1SectionsSectionIDGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/sections/{section_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetSectionAPIV1SectionsSectionIDGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetSectionAPIV1SectionsSectionIDGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetSectionAPIV1SectionsSectionIDGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/sections/{section_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetTaskAPIV1TasksTaskIDGet Get Task
func (c *Client) GetTaskAPIV1TasksTaskIDGet(ctx context.Context, options *GetTaskAPIV1TasksTaskIDGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTaskAPIV1TasksTaskIDGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks/{task_id}",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetTaskAPIV1TasksTaskIDGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetTaskAPIV1TasksTaskIDGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetTaskAPIV1TasksTaskIDGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks/{task_id}")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// GetTasksAPIV1TasksGet Get Tasks
func (c *Client) GetTasksAPIV1TasksGet(ctx context.Context, options *GetTasksAPIV1TasksGetRequestOptions, reqEditors ...runtime.RequestEditorFn) (*GetTasksAPIV1TasksGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/tasks",
		Method:     "GET",
		Options:    options,
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*GetTasksAPIV1TasksGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(GetTasksAPIV1TasksGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "GetTasksAPIV1TasksGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/tasks")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

// UserInfoAPIV1UserGet User Info
func (c *Client) UserInfoAPIV1UserGet(ctx context.Context, reqEditors ...runtime.RequestEditorFn) (*UserInfoAPIV1UserGetResponse, error) {
	var err error
	reqParams := runtime.RequestOptionsParameters{
		RequestURL: c.apiClient.GetBaseURL() + "/api/v1/user",
		Method:     "GET",
	}

	req, err := c.apiClient.CreateRequest(ctx, reqParams, reqEditors...)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}

	responseParser := func(ctx context.Context, resp *runtime.Response) (*UserInfoAPIV1UserGetResponse, error) {
		bodyBytes := resp.Content
		if resp.StatusCode != 200 {
			return nil, runtime.NewClientAPIError(fmt.Errorf("unexpected status code: %d", resp.StatusCode),
				runtime.WithStatusCode(resp.StatusCode))
		}
		target := new(UserInfoAPIV1UserGetResponse)
		// Handle empty response body gracefully
		if len(bodyBytes) == 0 {
			return target, nil
		}
		if err = json.Unmarshal(bodyBytes, target); err != nil {
			return nil, &runtime.ResponseDecodeError{
				StatusCode:    resp.StatusCode,
				ContentType:   resp.Headers.Get("Content-Type"),
				ContentLength: len(bodyBytes),
				TargetType:    "UserInfoAPIV1UserGetResponse",
				Body:          bodyBytes,
				Err:           err,
			}
		}
		return target, nil
	}

	resp, err := c.apiClient.ExecuteRequest(ctx, req, "/api/v1/user")
	if err != nil {
		return nil, fmt.Errorf("error executing request: %w", err)
	}
	return responseParser(ctx, resp)
}

var _ ClientInterface = (*Client)(nil)
