// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// ProjectStatus Project status.
//
// At the moment, this is for workspace projects only.
type ProjectStatus string

const (
	CANCELED   ProjectStatus = "CANCELED"
	COMPLETED  ProjectStatus = "COMPLETED"
	INPROGRESS ProjectStatus = "IN_PROGRESS"
	PAUSED     ProjectStatus = "PAUSED"
	PLANNED    ProjectStatus = "PLANNED"
)

// Validate checks if the ProjectStatus value is valid
func (p ProjectStatus) Validate() error {
	switch p {
	case CANCELED, COMPLETED, INPROGRESS, PAUSED, PLANNED:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProjectStatus value, got: %v", p))
	}
}

// ProjectVisibility Indicates who can see a project
type ProjectVisibility string

const (
	Public     ProjectVisibility = "public"
	Restricted ProjectVisibility = "restricted"
	Team       ProjectVisibility = "team"
)

// Validate checks if the ProjectVisibility value is valid
func (p ProjectVisibility) Validate() error {
	switch p {
	case Public, Restricted, Team:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProjectVisibility value, got: %v", p))
	}
}

type ThemeAppearance string

const (
	Dark   ThemeAppearance = "dark"
	Light  ThemeAppearance = "light"
	System ThemeAppearance = "system"
)

// Validate checks if the ThemeAppearance value is valid
func (t ThemeAppearance) Validate() error {
	switch t {
	case Dark, Light, System:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ThemeAppearance value, got: %v", t))
	}
}

// UrgentReminderDeviceViewDevicePlatform Registered device platform.
type UrgentReminderDeviceViewDevicePlatform string

const (
	Android UrgentReminderDeviceViewDevicePlatform = "android"
	Ios     UrgentReminderDeviceViewDevicePlatform = "ios"
)

// Validate checks if the UrgentReminderDeviceViewDevicePlatform value is valid
func (u UrgentReminderDeviceViewDevicePlatform) Validate() error {
	switch u {
	case Android, Ios:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UrgentReminderDeviceViewDevicePlatform value, got: %v", u))
	}
}

// UserJSONVerificationStatus User's email verification status. unverified (just signed up), verified (verified email or social login), blocked (failed to verify in 7 days), legacy (signed up before August 2022)
type UserJSONVerificationStatus string

const (
	Blocked    UserJSONVerificationStatus = "blocked"
	Legacy     UserJSONVerificationStatus = "legacy"
	Unverified UserJSONVerificationStatus = "unverified"
	Verified   UserJSONVerificationStatus = "verified"
)

// Validate checks if the UserJSONVerificationStatus value is valid
func (u UserJSONVerificationStatus) Validate() error {
	switch u {
	case Blocked, Legacy, Unverified, Verified:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONVerificationStatus value, got: %v", u))
	}
}

type UserJSONPremiumStatusAnyOf string

const (
	CurrentPersonalPlan UserJSONPremiumStatusAnyOf = "current_personal_plan"
	LegacyPersonalPlan  UserJSONPremiumStatusAnyOf = "legacy_personal_plan"
	NotPremium          UserJSONPremiumStatusAnyOf = "not_premium"
	TeamsBusinessMember UserJSONPremiumStatusAnyOf = "teams_business_member"
)

// Validate checks if the UserJSONPremiumStatusAnyOf value is valid
func (u UserJSONPremiumStatusAnyOf) Validate() error {
	switch u {
	case CurrentPersonalPlan, LegacyPersonalPlan, NotPremium, TeamsBusinessMember:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONPremiumStatusAnyOf value, got: %v", u))
	}
}

// UserJSONDateFormat Whether to use the DD-MM-YYYY date format (if set to 0), or the MM-DD-YYYY format (if set to 1)
type UserJSONDateFormat int

const (
	N0 UserJSONDateFormat = 0
	N1 UserJSONDateFormat = 1
)

// Validate checks if the UserJSONDateFormat value is valid
func (u UserJSONDateFormat) Validate() error {
	switch u {
	case N0, N1:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONDateFormat value, got: %v", u))
	}
}

type UserJSONTimeFormatAnyOf int

const (
	UserJSONTimeFormatAnyOfN0 UserJSONTimeFormatAnyOf = 0
	UserJSONTimeFormatAnyOfN1 UserJSONTimeFormatAnyOf = 1
)

// Validate checks if the UserJSONTimeFormatAnyOf value is valid
func (u UserJSONTimeFormatAnyOf) Validate() error {
	switch u {
	case UserJSONTimeFormatAnyOfN0, UserJSONTimeFormatAnyOfN1:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONTimeFormatAnyOf value, got: %v", u))
	}
}

// UserJSONSortOrder Whether to show projects in an oldest dates first order (if set to 0), or a oldest dates last order (if set to 1)
type UserJSONSortOrder int

const (
	UserJSONSortOrderN0 UserJSONSortOrder = 0
	UserJSONSortOrderN1 UserJSONSortOrder = 1
)

// Validate checks if the UserJSONSortOrder value is valid
func (u UserJSONSortOrder) Validate() error {
	switch u {
	case UserJSONSortOrderN0, UserJSONSortOrderN1:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONSortOrder value, got: %v", u))
	}
}

// UserJSONLang The user's language
type UserJSONLang string

const (
	Cs   UserJSONLang = "cs"
	Da   UserJSONLang = "da"
	De   UserJSONLang = "de"
	En   UserJSONLang = "en"
	Es   UserJSONLang = "es"
	Fi   UserJSONLang = "fi"
	Fr   UserJSONLang = "fr"
	It   UserJSONLang = "it"
	Ja   UserJSONLang = "ja"
	Ko   UserJSONLang = "ko"
	Nl   UserJSONLang = "nl"
	Pl   UserJSONLang = "pl"
	PtBR UserJSONLang = "pt_BR"
	Ru   UserJSONLang = "ru"
	Sv   UserJSONLang = "sv"
	Tr   UserJSONLang = "tr"
	ZhCN UserJSONLang = "zh_CN"
	ZhTW UserJSONLang = "zh_TW"
)

// Validate checks if the UserJSONLang value is valid
func (u UserJSONLang) Validate() error {
	switch u {
	case Cs, Da, De, En, Es, Fi, Fr, It, Ja, Ko, Nl, Pl, PtBR, Ru, Sv, Tr, ZhCN, ZhTW:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONLang value, got: %v", u))
	}
}

type UserJSONKarmaTrendAnyOf string

const (
	Down  UserJSONKarmaTrendAnyOf = "down"
	Minus UserJSONKarmaTrendAnyOf = "-"
	Up    UserJSONKarmaTrendAnyOf = "up"
)

// Validate checks if the UserJSONKarmaTrendAnyOf value is valid
func (u UserJSONKarmaTrendAnyOf) Validate() error {
	switch u {
	case Down, Minus, Up:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONKarmaTrendAnyOf value, got: %v", u))
	}
}

type UserJSONOnboardingLevelAnyOf string

const (
	Beginner     UserJSONOnboardingLevelAnyOf = "beginner"
	Intermediate UserJSONOnboardingLevelAnyOf = "intermediate"
	Pro          UserJSONOnboardingLevelAnyOf = "pro"
)

// Validate checks if the UserJSONOnboardingLevelAnyOf value is valid
func (u UserJSONOnboardingLevelAnyOf) Validate() error {
	switch u {
	case Beginner, Intermediate, Pro:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONOnboardingLevelAnyOf value, got: %v", u))
	}
}

type UserJSONOnboardingPersonaAnyOf string

const (
	Analog   UserJSONOnboardingPersonaAnyOf = "analog"
	Calendar UserJSONOnboardingPersonaAnyOf = "calendar"
	Organic  UserJSONOnboardingPersonaAnyOf = "organic"
	Tasks    UserJSONOnboardingPersonaAnyOf = "tasks"
)

// Validate checks if the UserJSONOnboardingPersonaAnyOf value is valid
func (u UserJSONOnboardingPersonaAnyOf) Validate() error {
	switch u {
	case Analog, Calendar, Organic, Tasks:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONOnboardingPersonaAnyOf value, got: %v", u))
	}
}

type UserJSONOnboardingRoleAnyOf string

const (
	Founder UserJSONOnboardingRoleAnyOf = "founder"
	Ic      UserJSONOnboardingRoleAnyOf = "ic"
	Leader  UserJSONOnboardingRoleAnyOf = "leader"
)

// Validate checks if the UserJSONOnboardingRoleAnyOf value is valid
func (u UserJSONOnboardingRoleAnyOf) Validate() error {
	switch u {
	case Founder, Ic, Leader:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONOnboardingRoleAnyOf value, got: %v", u))
	}
}

type UserJSONOnboardingUseCasesAnyOf string

const (
	Education   UserJSONOnboardingUseCasesAnyOf = "education"
	Personal    UserJSONOnboardingUseCasesAnyOf = "personal"
	Simple      UserJSONOnboardingUseCasesAnyOf = "simple"
	Solo        UserJSONOnboardingUseCasesAnyOf = "solo"
	Teamcreator UserJSONOnboardingUseCasesAnyOf = "teamcreator"
	Teamjoiner  UserJSONOnboardingUseCasesAnyOf = "teamjoiner"
	Teamwork    UserJSONOnboardingUseCasesAnyOf = "teamwork"
	Work        UserJSONOnboardingUseCasesAnyOf = "work"
)

// Validate checks if the UserJSONOnboardingUseCasesAnyOf value is valid
func (u UserJSONOnboardingUseCasesAnyOf) Validate() error {
	switch u {
	case Education, Personal, Simple, Solo, Teamcreator, Teamjoiner, Teamwork, Work:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UserJSONOnboardingUseCasesAnyOf value, got: %v", u))
	}
}
