// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type ReopenTaskAPIV1TasksTaskIDReopenPostPath struct {
	TaskID string `json:"task_id" validate:"required"`
}

func (r ReopenTaskAPIV1TasksTaskIDReopenPostPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type CloseTaskAPIV1TasksTaskIDClosePostPath struct {
	TaskID string `json:"task_id" validate:"required"`
}

func (c CloseTaskAPIV1TasksTaskIDClosePostPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type GetProjectAPIV1ProjectsProjectIDGetPath struct {
	ProjectID string `json:"project_id" validate:"required"`
}

func (g GetProjectAPIV1ProjectsProjectIDGetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetSectionAPIV1SectionsSectionIDGetPath struct {
	SectionID string `json:"section_id" validate:"required"`
}

func (g GetSectionAPIV1SectionsSectionIDGetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetTaskAPIV1TasksTaskIDGetPath struct {
	TaskID string `json:"task_id" validate:"required"`
}

func (g GetTaskAPIV1TasksTaskIDGetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}
