// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetQuery struct {
	Since       time.Time `json:"since" validate:"required"`
	Until       time.Time `json:"until" validate:"required"`
	WorkspaceID *int      `json:"workspace_id,omitempty"`
	ProjectID   *string   `json:"project_id,omitempty"`
	SectionID   *string   `json:"section_id,omitempty"`
	ParentID    *string   `json:"parent_id,omitempty"`
	FilterQuery *string   `json:"filter_query,omitempty"`
	FilterLang  *string   `json:"filter_lang,omitempty"`
	Cursor      *string   `json:"cursor,omitempty"`
	Limit       *int      `json:"limit,omitempty"`
	PublicKey   *string   `json:"public_key,omitempty"`
}

func (t TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(t))
}

type GetSectionAPIV1SectionsSectionIDGetQuery struct {
	PublicKey *string `json:"public_key,omitempty"`
}

type GetTaskAPIV1TasksTaskIDGetQuery struct {
	PublicKey *string `json:"public_key,omitempty"`
}

type GetTasksAPIV1TasksGetQuery struct {
	ProjectID *string `json:"project_id,omitempty"`
	SectionID *string `json:"section_id,omitempty"`
	ParentID  *string `json:"parent_id,omitempty"`
	Label     *string `json:"label,omitempty"`
	Ids       *string `json:"ids,omitempty"`
	Cursor    *string `json:"cursor,omitempty"`
	Limit     *int    `json:"limit,omitempty" validate:"omitempty,lte=200"`
}

func (g GetTasksAPIV1TasksGetQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}
