// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import "net/http"

type TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse = TasksCompletedDateResponse

type ReopenTaskAPIV1TasksTaskIDReopenPostResponse struct{}

type CloseTaskAPIV1TasksTaskIDClosePostResponse struct{}

// GetProjectAPIV1ProjectsProjectIDGetResponse Can be either a personal or a workspace project.
type GetProjectAPIV1ProjectsProjectIDGetResponse = AnyProjectSyncViewResponse

// GetSectionAPIV1SectionsSectionIDGetResponse A class with fields representing a SectionView which will be returned
// to clients in a sync (or sync-like) response.
type GetSectionAPIV1SectionsSectionIDGetResponse = SectionSyncView

// GetTaskAPIV1TasksTaskIDGetResponse A class with fields representing an ItemView which will be returned to
// clients in a sync (or sync-like) response.
type GetTaskAPIV1TasksTaskIDGetResponse = ItemSyncView

type GetTasksAPIV1TasksGetResponse = PaginatedListItemSyncView

// UserInfoAPIV1UserGetResponse A model for the user objects returned by the sync/REST API.
//
// This model is used purely for OpenAPI documentation generation and does not
// handle actual serialization (which is handled by @todoist.models.json.user.generate).
type UserInfoAPIV1UserGetResponse = UserJSON

type TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *TasksCompletedByCompletionDateAPIV1TasksCompletedByCompletionDateGetResponse
}

type ReopenTaskAPIV1TasksTaskIDReopenPostResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *ReopenTaskAPIV1TasksTaskIDReopenPostResponse
}

type CloseTaskAPIV1TasksTaskIDClosePostResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *CloseTaskAPIV1TasksTaskIDClosePostResponse
}

type GetProjectAPIV1ProjectsProjectIDGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *GetProjectAPIV1ProjectsProjectIDGetResponse
}

type GetSectionAPIV1SectionsSectionIDGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *GetSectionAPIV1SectionsSectionIDGetResponse
}

type GetTaskAPIV1TasksTaskIDGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *GetTaskAPIV1TasksTaskIDGetResponse
}

type GetTasksAPIV1TasksGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *GetTasksAPIV1TasksGetResponse
}

type UserInfoAPIV1UserGetResp struct {
	HTTPResponse *http.Response
	Body         []byte
	StatusCode   int
	JSON200      *UserInfoAPIV1UserGetResponse
}
