// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

// AnyProjectSyncViewResponse Can be either a personal or a workspace project.
type AnyProjectSyncViewResponse struct {
	AnyProjectSyncViewResponse_AnyOf *AnyProjectSyncViewResponse_AnyOf `json:"-"`
}

func (a AnyProjectSyncViewResponse) Validate() error {
	var errors runtime.ValidationErrors
	if a.AnyProjectSyncViewResponse_AnyOf != nil {
		if v, ok := any(a.AnyProjectSyncViewResponse_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("AnyProjectSyncViewResponse_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (a AnyProjectSyncViewResponse) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(a.AnyProjectSyncViewResponse_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("AnyProjectSyncViewResponse_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (a *AnyProjectSyncViewResponse) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if a.AnyProjectSyncViewResponse_AnyOf == nil {
		a.AnyProjectSyncViewResponse_AnyOf = &AnyProjectSyncViewResponse_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, a.AnyProjectSyncViewResponse_AnyOf); err != nil {
		return fmt.Errorf("AnyProjectSyncViewResponse_AnyOf unmarshal: %w", err)
	}

	return nil
}

// ItemSyncView A class with fields representing an ItemView which will be returned to
// clients in a sync (or sync-like) response.
type ItemSyncView struct {
	// UserID String ID of the user who owns the task.
	UserID string `json:"user_id" validate:"required"`

	// ID String ID of the task.
	ID string `json:"id" validate:"required"`

	// ProjectID String ID of the project that contains the task.
	ProjectID string `json:"project_id" validate:"required"`

	// SectionID String ID of the section that contains the task, or `null` if the task is not in a section.
	SectionID string `json:"section_id"`

	// ParentID String ID of the parent task, or `null` if this is a top-level task.
	ParentID string `json:"parent_id"`

	// AddedByUID String ID of the user who created the task, or `null` if unknown.
	AddedByUID string `json:"added_by_uid"`

	// AssignedByUID String ID of the user who assigned the task, or `null` if unassigned.
	AssignedByUID string `json:"assigned_by_uid"`

	// ResponsibleUID String ID of the user responsible for the task, or `null` if unassigned.
	ResponsibleUID string `json:"responsible_uid"`

	// Labels Names of labels attached to the task.
	Labels []string `json:"labels" validate:"required"`

	// Deadline Deadline details for the task, or `null` when the task has no deadline.
	Deadline map[string]string `json:"deadline"`

	// Duration Task duration details, or `null` when the task has no duration.
	Duration map[string]ItemSyncView_Duration_AnyOf_AdditionalProperties `json:"duration"`

	// IsCollapsed Whether the task is collapsed in the user's view.
	IsCollapsed bool `json:"is_collapsed"`

	// Checked Whether the task is completed.
	Checked bool `json:"checked"`

	// IsDeleted Whether the task is deleted.
	IsDeleted bool `json:"is_deleted"`

	// AddedAt Date and time when the task was created, or `null` if unknown.
	AddedAt string `json:"added_at"`

	// CompletedAt Date and time when the task was completed, or `null` if active.
	CompletedAt string `json:"completed_at"`

	// CompletedByUID String ID of the user who completed the task, or `null` if active.
	CompletedByUID string `json:"completed_by_uid"`

	// UpdatedAt Date and time when the task was last updated, or `null` if unknown.
	UpdatedAt string `json:"updated_at"`

	// Due Due date details for the task, or `null` when the task has no due date.
	Due map[string]any `json:"due"`

	// Priority Task priority from 1 (normal) to 4 (urgent).
	Priority int `json:"priority"`

	// ChildOrder Position of the task among sibling tasks.
	ChildOrder int `json:"child_order"`

	// OrderKey Fractional-indexing order key: tasks sort by comparing keys lexicographically among siblings sharing the same project, section and parent task. May be `null` for tasks not yet migrated.
	OrderKey string `json:"order_key"`

	// Content Task content.
	Content string `json:"content" validate:"required"`

	// Description Task description.
	Description string `json:"description" validate:"required"`

	// NoteCount **Deprecated**: only returns 0 and is marked for removal.
	NoteCount int `json:"note_count"`

	// DayOrder Task order for day-based views.
	DayOrder int `json:"day_order"`

	// CompletedCount Number of times the task has been marked as completed. Increments on every completion, including recurring occurrences and re-completions of a previously reopened task. Decremented when a recurring completion is undone.
	CompletedCount int `json:"completed_count"`

	// PostponedCount Number of times the task's due date has been rescheduled by the user. Increments on any due-date change between two set dates (forward or backward); recurring completions and undos are not counted.
	PostponedCount int `json:"postponed_count"`
}

func (i ItemSyncView) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(i.UserID, "required"); err != nil {
		errors = errors.Append("UserID", err)
	}
	if err := typesValidator.Var(i.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(i.ProjectID, "required"); err != nil {
		errors = errors.Append("ProjectID", err)
	}
	if err := typesValidator.Var(i.Labels, "required"); err != nil {
		errors = errors.Append("Labels", err)
	}
	for k, v := range i.Duration {
		if validator, ok := any(v).(runtime.Validator); ok {
			if err := validator.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Duration[%s]", k), err)
			}
		}
	}
	if err := typesValidator.Var(i.Content, "required"); err != nil {
		errors = errors.Append("Content", err)
	}
	if err := typesValidator.Var(i.Description, "required"); err != nil {
		errors = errors.Append("Description", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type PaginatedListItemSyncView struct {
	// Results Objects in the current page of results.
	Results []ItemSyncView `json:"results" validate:"required"`

	// NextCursor Cursor for the next page of results, or `null` when there are no more results.
	NextCursor string `json:"next_cursor"`
}

func (p PaginatedListItemSyncView) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range p.Results {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Results[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// PersonalProjectSyncView A representation of a Personal Project Sync View, extending the base ProjectSync
// View, to be returned to clients in a sync (or sync-like) response.
type PersonalProjectSyncView struct {
	// ID String ID of the project.
	ID string `json:"id" validate:"required"`

	// CanAssignTasks Whether the current user can assign tasks in the project.
	CanAssignTasks bool `json:"can_assign_tasks"`

	// CanComment Whether the current user can comment in the project.
	CanComment bool `json:"can_comment"`

	// ChildOrder Position of the project among sibling projects.
	ChildOrder int `json:"child_order"`

	// OrderKey Fractional-indexing order key among sibling projects, or `null` until assigned (backfill in progress). Always `null` for workspace projects, which are ordered via folders instead.
	OrderKey string `json:"order_key"`

	// IsCollapsed Whether the project is collapsed in the user's view.
	IsCollapsed bool `json:"is_collapsed"`

	// Color Project color name.
	Color string `json:"color" validate:"required"`

	// CreatorUID String ID of the user who created the project.
	CreatorUID string `json:"creator_uid"`

	// CreatedAt Date and time when the project was created, or `null` if unknown.
	CreatedAt string `json:"created_at"`

	// IsArchived Whether the project is archived.
	IsArchived bool `json:"is_archived"`

	// IsDeleted Whether the project is deleted.
	IsDeleted bool `json:"is_deleted"`

	// IsFavorite Whether the project is marked as a favorite.
	IsFavorite bool `json:"is_favorite"`

	// IsFrozen Whether the project is frozen and cannot be modified.
	IsFrozen bool `json:"is_frozen"`

	// Name Project name.
	Name string `json:"name" validate:"required"`

	// IsShared Whether the project is shared with other users.
	IsShared bool `json:"is_shared"`

	// UpdatedAt Date and time when the project was last updated, or `null` if unknown.
	UpdatedAt string `json:"updated_at"`

	// ViewStyle Project view style.
	ViewStyle string `json:"view_style" validate:"required"`

	// DefaultOrder Default order of the project in team views.
	DefaultOrder int `json:"default_order"`

	// DefaultOrderKey Fractional-indexing key for the workspace's shared default-ordering scope (folders and workspace projects together). `null` for personal projects, and for workspace projects not yet assigned one (backfill pending).
	DefaultOrderKey string `json:"default_order_key"`

	// Description Project description.
	Description string `json:"description" validate:"required"`

	// PublicKey Public access key for the project, or an empty string when public access is disabled.
	PublicKey string `json:"public_key" validate:"required"`

	// Access Project access configuration.
	Access ProjectAccessView `json:"access"`

	// Role Current user's role in the project.
	Role string `json:"role"`

	// ParentID String ID of the parent project, or `null` for root projects.
	ParentID string `json:"parent_id"`

	// InboxProject Whether this project is the user's Inbox project.
	InboxProject bool `json:"inbox_project"`
}

func (p PersonalProjectSyncView) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(p.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(p.Color, "required"); err != nil {
		errors = errors.Append("Color", err)
	}
	if err := typesValidator.Var(p.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if err := typesValidator.Var(p.ViewStyle, "required"); err != nil {
		errors = errors.Append("ViewStyle", err)
	}
	if err := typesValidator.Var(p.Description, "required"); err != nil {
		errors = errors.Append("Description", err)
	}
	if err := typesValidator.Var(p.PublicKey, "required"); err != nil {
		errors = errors.Append("PublicKey", err)
	}
	if v, ok := any(p.Access).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Access", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// ProjectAccessView Contains the details on who can view a project.
type ProjectAccessView struct {
	// Visibility Indicates who can see a project
	Visibility ProjectVisibility `json:"visibility" validate:"required"`

	// Configuration Configuration for the selected visibility level.
	Configuration ProjectAccessView_Configuration `json:"configuration"`
}

func (p ProjectAccessView) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(p.Visibility).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Visibility", err)
		}
	}
	if v, ok := any(p.Configuration).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Configuration", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// ProjectAccessView_Configuration Configuration for the selected visibility level.
type ProjectAccessView_Configuration struct {
	ProjectAccessView_Configuration_AnyOf *ProjectAccessView_Configuration_AnyOf `json:"-"`
}

func (p ProjectAccessView_Configuration) Validate() error {
	var errors runtime.ValidationErrors
	if p.ProjectAccessView_Configuration_AnyOf != nil {
		if v, ok := any(p.ProjectAccessView_Configuration_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ProjectAccessView_Configuration_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (p ProjectAccessView_Configuration) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(p.ProjectAccessView_Configuration_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("ProjectAccessView_Configuration_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (p *ProjectAccessView_Configuration) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if p.ProjectAccessView_Configuration_AnyOf == nil {
		p.ProjectAccessView_Configuration_AnyOf = &ProjectAccessView_Configuration_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, p.ProjectAccessView_Configuration_AnyOf); err != nil {
		return fmt.Errorf("ProjectAccessView_Configuration_AnyOf unmarshal: %w", err)
	}

	return nil
}

// PublicProjectConfiguration Configuration specific to public projects.
type PublicProjectConfiguration struct {
	// HideCollaboratorDetails Whether collaborator details are hidden on the public project.
	HideCollaboratorDetails bool `json:"hide_collaborator_details"`

	// DisableDuplication Whether public project duplication is disabled.
	DisableDuplication bool `json:"disable_duplication"`
}

// RestrictedProjectConfiguration Configuration specific to restricted projects.
type RestrictedProjectConfiguration = map[string]any

// SectionSyncView A class with fields representing a SectionView which will be returned
// to clients in a sync (or sync-like) response.
type SectionSyncView struct {
	// ID String ID of the section.
	ID string `json:"id" validate:"required"`

	// UserID String ID of the user who owns the section.
	UserID string `json:"user_id" validate:"required"`

	// ProjectID String ID of the project that contains the section.
	ProjectID string `json:"project_id" validate:"required"`

	// AddedAt Date and time when the section was created.
	AddedAt time.Time `json:"added_at" validate:"required"`

	// UpdatedAt Date and time when the section was last updated, or `null` if unknown.
	UpdatedAt string `json:"updated_at"`

	// ArchivedAt Date and time when the section was archived, or `null` if it is active.
	ArchivedAt string `json:"archived_at"`

	// Name Section name.
	Name string `json:"name" validate:"required"`

	// Description Section description, or `null` if it has none.
	Description string `json:"description"`

	// SectionOrder Position of the section in the project.
	SectionOrder int `json:"section_order"`

	// OrderKey Fractional-indexing order key: sections sort by comparing keys lexicographically within a project. May be `null` for projects not yet migrated.
	OrderKey string `json:"order_key"`

	// IsCollapsed Whether the section is collapsed in the user's view.
	IsCollapsed bool `json:"is_collapsed"`

	// IsArchived Whether the section is archived.
	IsArchived bool `json:"is_archived"`

	// IsDeleted Whether the section is deleted.
	IsDeleted bool `json:"is_deleted"`
}

func (s SectionSyncView) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type TasksCompletedDateResponse struct {
	// Items Completed tasks in the current page.
	Items []ItemSyncView `json:"items,omitempty"`

	// NextCursor Cursor for the next page of completed tasks, when more results are available. Omitted when there is no next page.
	NextCursor *string `json:"next_cursor,omitempty"`
}

func (t TasksCompletedDateResponse) Validate() error {
	var errors runtime.ValidationErrors
	for i, item := range t.Items {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Items[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// TeamProjectConfiguration Configuration specific to team projects.
type TeamProjectConfiguration = map[string]any

type UrgentReminderDeviceView struct {
	// DevicePlatform Registered device platform.
	DevicePlatform UrgentReminderDeviceViewDevicePlatform `json:"device_platform" validate:"required"`

	// DeviceID Registered device ID.
	DeviceID string `json:"device_id" validate:"required"`

	// DeviceToken Registered device token.
	DeviceToken string `json:"device_token" validate:"required"`

	// DeviceName Registered device name when available.
	DeviceName *string `json:"device_name,omitempty"`
}

func (u UrgentReminderDeviceView) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DevicePlatform).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DevicePlatform", err)
		}
	}
	if err := typesValidator.Var(u.DeviceID, "required"); err != nil {
		errors = errors.Append("DeviceID", err)
	}
	if err := typesValidator.Var(u.DeviceToken, "required"); err != nil {
		errors = errors.Append("DeviceToken", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// UserJSON A model for the user objects returned by the sync/REST API.
//
// This model is used purely for OpenAPI documentation generation and does not
// handle actual serialization (which is handled by @todoist.models.json.user.generate).
type UserJSON struct {
	// ID User ID
	ID string `json:"id" validate:"required"`

	// Email User's email address
	Email string `json:"email" validate:"required"`

	// FullName The user's real name formatted as Firstname Lastname
	FullName string `json:"full_name" validate:"required"`

	// HasPassword Whether the user has a password set on the account. It will be false if they have only authenticated without a password (e.g. using Google, Facebook, etc.)
	HasPassword bool `json:"has_password"`

	// VerificationStatus User's email verification status. unverified (just signed up), verified (verified email or social login), blocked (failed to verify in 7 days), legacy (signed up before August 2022)
	VerificationStatus UserJSONVerificationStatus `json:"verification_status" validate:"required"`

	// MfaEnabled Whether multi-factor authentication is enabled
	MfaEnabled bool `json:"mfa_enabled"`

	// Token The user's token that should be used to call the other API methods
	Token *string `json:"token,omitempty"`

	// IsPremium Whether the user has a Todoist Pro subscription (a true or false value)
	IsPremium bool `json:"is_premium"`

	// PremiumStatus Outlines why a user is premium, possible values are: not_premium, current_personal_plan, legacy_personal_plan or teams_business_member
	PremiumStatus *UserJSONPremiumStatusAnyOf `json:"premium_status,omitempty"`

	// PremiumUntil The date when the user's Todoist Pro subscription ends (null if not a Todoist Pro user). This should be used for informational purposes only as this does not include the grace period upon expiration
	PremiumUntil *string `json:"premium_until,omitempty"`

	// FreeTrialExpires Date when free trial expires (ISO 8601 format)
	FreeTrialExpires *string `json:"free_trial_expires,omitempty"`

	// HasStartedATrial Whether the user has ever started a free trial
	HasStartedATrial bool `json:"has_started_a_trial"`

	// JoinedAt Date when user joined Todoist (ISO 8601 format)
	JoinedAt *string `json:"joined_at,omitempty"`

	// IsDeleted Whether the user is deleted
	IsDeleted *bool `json:"is_deleted,omitempty"`

	// DeletedAt Date when user was deleted (ISO 8601 format)
	DeletedAt *string `json:"deleted_at,omitempty"`

	// BusinessAccountID The ID of the user's business account
	BusinessAccountID *int `json:"business_account_id,omitempty"`

	// DateFormat Whether to use the DD-MM-YYYY date format (if set to 0), or the MM-DD-YYYY format (if set to 1)
	DateFormat UserJSONDateFormat `json:"date_format"`

	// TimeFormat Whether to use a 24h format such as 13:00 (if set to 0) when displaying time, or a 12h format such as 1:00pm (if set to 1)
	TimeFormat *UserJSONTimeFormatAnyOf `json:"time_format,omitempty"`

	// SortOrder Whether to show projects in an oldest dates first order (if set to 0), or a oldest dates last order (if set to 1)
	SortOrder UserJSONSortOrder `json:"sort_order"`

	// ThemeID The currently selected Todoist theme (a number between 0 and 13)
	ThemeID         string          `json:"theme_id" validate:"required"`
	ThemeAppearance ThemeAppearance `json:"theme_appearance" validate:"required"`

	// StartDay The first day of the week (between 1 and 7, where 1 is Monday and 7 is Sunday)
	StartDay int `json:"start_day" validate:"gte=1,lte=7"`

	// WeekendStartDay The day used when a user chooses to schedule a task for the 'Weekend' (between 1 and 7, where 1 is Monday and 7 is Sunday)
	WeekendStartDay int `json:"weekend_start_day" validate:"gte=1,lte=7"`

	// NextWeek The day of the next week, that tasks will be postponed to (between 1 and 7, where 1 is Monday and 7 is Sunday)
	NextWeek int `json:"next_week" validate:"gte=1,lte=7"`

	// AutoReminder The default time in minutes for the automatic reminders set, whenever a due date has been specified for a task
	AutoReminder int `json:"auto_reminder"`

	// UrgentReminderDevice The device that should ring urgent reminders. Contains device_id, device_token, device_platform (ios or android), and optionally device_name.
	UrgentReminderDevice *UrgentReminderDeviceView `json:"urgent_reminder_device,omitempty"`

	// StartPage The user's default view on Todoist. The start page can be one of the following: inbox, teaminbox, today, next7days, upcoming, assigned_to_me, project?id=1234 to open a project, label?name=abc to open a label, filter?id=1234 to open a filter, or workspace_filter?id=1234 to open a workspace filter
	StartPage string `json:"start_page" validate:"required"`

	// InboxProjectID The ID of the user's Inbox project
	InboxProjectID *string `json:"inbox_project_id,omitempty"`

	// Lang The user's language
	Lang UserJSONLang `json:"lang" validate:"required"`

	// TzInfo The user's timezone (a dictionary structure), which includes the following elements: the timezone as a string value, the hours and minutes difference from GMT, whether daylight saving time applies denoted by is_dst, and a string value of the time difference from GMT that is gmt_string
	TzInfo map[string]any `json:"tz_info"`

	// Karma The user's karma score
	Karma float32 `json:"karma"`

	// KarmaTrend The user's karma trend. Can be 'up', 'down', or '-' (no change)
	KarmaTrend *UserJSONKarmaTrendAnyOf `json:"karma_trend,omitempty"`

	// DailyGoal The daily goal number of completed tasks for karma
	DailyGoal int `json:"daily_goal"`

	// WeeklyGoal The target number of tasks to complete per week
	WeeklyGoal int `json:"weekly_goal"`

	// DaysOff Array of integers representing user's days off (between 1 and 7, where 1 is Monday and 7 is Sunday)
	DaysOff []int `json:"days_off" validate:"required"`

	// IsCelebrationsEnabled Whether celebration animations are enabled
	IsCelebrationsEnabled bool `json:"is_celebrations_enabled"`

	// CompletedCount Total number of tasks completed by user
	CompletedCount int `json:"completed_count"`

	// CompletedToday Number of tasks completed today by the user
	CompletedToday int `json:"completed_today"`

	// ShareLimit Maximum number of collaborators allowed in shared projects
	ShareLimit int `json:"share_limit"`

	// Features Feature flags and settings for the user
	Features map[string]any `json:"features"`

	// FeatureIdentifier Feature identifier for feature flag evaluations
	FeatureIdentifier string `json:"feature_identifier" validate:"required"`

	// JoinableWorkspace Information about workspaces the user can join
	JoinableWorkspace map[string]any `json:"joinable_workspace"`

	// OnboardingCompleted Whether the user has completed onboarding
	OnboardingCompleted bool `json:"onboarding_completed"`

	// OnboardingInitiated Whether the user has initiated onboarding
	OnboardingInitiated bool `json:"onboarding_initiated"`

	// OnboardingStarted Whether the user has started onboarding
	OnboardingStarted bool `json:"onboarding_started"`

	// OnboardingLevel User's self-reported skill level during onboarding
	OnboardingLevel *UserJSONOnboardingLevelAnyOf `json:"onboarding_level,omitempty"`

	// OnboardingPersona User's onboarding persona selection
	OnboardingPersona *UserJSONOnboardingPersonaAnyOf `json:"onboarding_persona,omitempty"`

	// OnboardingRole User's role selection during onboarding
	OnboardingRole *UserJSONOnboardingRoleAnyOf `json:"onboarding_role,omitempty"`

	// OnboardingTeamMode Whether user selected team mode during onboarding
	OnboardingTeamMode *string `json:"onboarding_team_mode,omitempty"`

	// OnboardingUseCases Use cases the user selected during onboarding
	OnboardingUseCases []UserJSONOnboardingUseCasesAnyOf `json:"onboarding_use_cases,omitempty"`

	// GettingStartedGuideProjects List of project IDs for getting started guide
	GettingStartedGuideProjects []string `json:"getting_started_guide_projects,omitempty"`

	// OnboardedDatedTasksCreated True once the user has created at least 1 task with a due date that includes a time component (excluding auto-seeded getting-started-guide tasks).
	OnboardedDatedTasksCreated *bool `json:"onboarded_dated_tasks_created,omitempty"`

	// OnboardedTasksCompleted True once the user has completed at least 3 tasks.
	OnboardedTasksCompleted *bool `json:"onboarded_tasks_completed,omitempty"`

	// OnboardedMobileAccessed True once the user has synced from iOS or Android.
	OnboardedMobileAccessed *bool `json:"onboarded_mobile_accessed,omitempty"`

	// OnboardedDesktopAccessed True once the user has synced from Web, macOS, or Windows.
	OnboardedDesktopAccessed *bool `json:"onboarded_desktop_accessed,omitempty"`

	// IsOnboarded Composite flag: true once all four onboarded_* criteria above are met.
	IsOnboarded *bool `json:"is_onboarded,omitempty"`

	// ActivatedUser Whether the user is considered activated (completed key onboarding actions)
	ActivatedUser bool `json:"activated_user"`

	// HasMagicNumber Whether the user has reached a magic number milestone
	HasMagicNumber bool `json:"has_magic_number"`

	// ImageID The ID of the user's avatar
	ImageID *string `json:"image_id,omitempty"`

	// AvatarBig The link to a 195x195 pixels image of the user's avatar
	AvatarBig *string `json:"avatar_big,omitempty"`

	// AvatarMedium The link to a 60x60 pixels image of the user's avatar
	AvatarMedium *string `json:"avatar_medium,omitempty"`

	// AvatarS640 The link to a 640x640 pixels image of the user's avatar
	AvatarS640 *string `json:"avatar_s640,omitempty"`

	// AvatarSmall The link to a 35x35 pixels image of the user's avatar
	AvatarSmall *string `json:"avatar_small,omitempty"`

	// WebsocketURL WebSocket URL for real-time updates
	WebsocketURL string `json:"websocket_url" validate:"required"`
}

func (u UserJSON) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(u.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(u.Email, "required"); err != nil {
		errors = errors.Append("Email", err)
	}
	if err := typesValidator.Var(u.FullName, "required"); err != nil {
		errors = errors.Append("FullName", err)
	}
	if v, ok := any(u.VerificationStatus).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("VerificationStatus", err)
		}
	}
	if u.PremiumStatus != nil {
		if v, ok := any(u.PremiumStatus).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PremiumStatus", err)
			}
		}
	}
	if v, ok := any(u.DateFormat).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DateFormat", err)
		}
	}
	if u.TimeFormat != nil {
		if v, ok := any(u.TimeFormat).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("TimeFormat", err)
			}
		}
	}
	if v, ok := any(u.SortOrder).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("SortOrder", err)
		}
	}
	if err := typesValidator.Var(u.ThemeID, "required"); err != nil {
		errors = errors.Append("ThemeID", err)
	}
	if v, ok := any(u.ThemeAppearance).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ThemeAppearance", err)
		}
	}
	if err := typesValidator.Var(u.StartDay, "gte=1,lte=7"); err != nil {
		errors = errors.Append("StartDay", err)
	}
	if err := typesValidator.Var(u.WeekendStartDay, "gte=1,lte=7"); err != nil {
		errors = errors.Append("WeekendStartDay", err)
	}
	if err := typesValidator.Var(u.NextWeek, "gte=1,lte=7"); err != nil {
		errors = errors.Append("NextWeek", err)
	}
	if u.UrgentReminderDevice != nil {
		if v, ok := any(u.UrgentReminderDevice).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("UrgentReminderDevice", err)
			}
		}
	}
	if err := typesValidator.Var(u.StartPage, "required"); err != nil {
		errors = errors.Append("StartPage", err)
	}
	if v, ok := any(u.Lang).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Lang", err)
		}
	}
	if u.KarmaTrend != nil {
		if v, ok := any(u.KarmaTrend).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("KarmaTrend", err)
			}
		}
	}
	if err := typesValidator.Var(u.DaysOff, "required"); err != nil {
		errors = errors.Append("DaysOff", err)
	}
	if err := typesValidator.Var(u.FeatureIdentifier, "required"); err != nil {
		errors = errors.Append("FeatureIdentifier", err)
	}
	if u.OnboardingLevel != nil {
		if v, ok := any(u.OnboardingLevel).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("OnboardingLevel", err)
			}
		}
	}
	if u.OnboardingPersona != nil {
		if v, ok := any(u.OnboardingPersona).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("OnboardingPersona", err)
			}
		}
	}
	if u.OnboardingRole != nil {
		if v, ok := any(u.OnboardingRole).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("OnboardingRole", err)
			}
		}
	}
	for i, item := range u.OnboardingUseCases {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("OnboardingUseCases[%d]", i), err)
			}
		}
	}
	if err := typesValidator.Var(u.WebsocketURL, "required"); err != nil {
		errors = errors.Append("WebsocketURL", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

// WorkspaceProjectSyncView A representation of a Workspace Project Sync View, extending the base ProjectSync
// View, to be returned to clients in a sync (or sync-like) response.
type WorkspaceProjectSyncView struct {
	// ID String ID of the project.
	ID string `json:"id" validate:"required"`

	// CanAssignTasks Whether the current user can assign tasks in the project.
	CanAssignTasks bool `json:"can_assign_tasks"`

	// CanComment Whether the current user can comment in the project.
	CanComment bool `json:"can_comment"`

	// ChildOrder Position of the project among sibling projects.
	ChildOrder int `json:"child_order"`

	// OrderKey Fractional-indexing order key among sibling projects, or `null` until assigned (backfill in progress). Always `null` for workspace projects, which are ordered via folders instead.
	OrderKey string `json:"order_key"`

	// IsCollapsed Whether the project is collapsed in the user's view.
	IsCollapsed bool `json:"is_collapsed"`

	// Color Project color name.
	Color string `json:"color" validate:"required"`

	// CreatorUID String ID of the user who created the project.
	CreatorUID string `json:"creator_uid"`

	// CreatedAt Date and time when the project was created, or `null` if unknown.
	CreatedAt string `json:"created_at"`

	// IsArchived Whether the project is archived.
	IsArchived bool `json:"is_archived"`

	// IsDeleted Whether the project is deleted.
	IsDeleted bool `json:"is_deleted"`

	// IsFavorite Whether the project is marked as a favorite.
	IsFavorite bool `json:"is_favorite"`

	// IsFrozen Whether the project is frozen and cannot be modified.
	IsFrozen bool `json:"is_frozen"`

	// Name Project name.
	Name string `json:"name" validate:"required"`

	// IsShared Whether the project is shared with other users.
	IsShared bool `json:"is_shared"`

	// UpdatedAt Date and time when the project was last updated, or `null` if unknown.
	UpdatedAt string `json:"updated_at"`

	// ViewStyle Project view style.
	ViewStyle string `json:"view_style" validate:"required"`

	// DefaultOrder Default order of the project in team views.
	DefaultOrder int `json:"default_order"`

	// DefaultOrderKey Fractional-indexing key for the workspace's shared default-ordering scope (folders and workspace projects together). `null` for personal projects, and for workspace projects not yet assigned one (backfill pending).
	DefaultOrderKey string `json:"default_order_key"`

	// Description Project description.
	Description string `json:"description" validate:"required"`

	// PublicKey Public access key for the project, or an empty string when public access is disabled.
	PublicKey string `json:"public_key" validate:"required"`

	// Access Project access configuration.
	Access ProjectAccessView `json:"access"`

	// Role Current user's role in the project.
	Role string `json:"role"`

	// CollaboratorRoleDefault Default collaborator role for the workspace project.
	CollaboratorRoleDefault string `json:"collaborator_role_default" validate:"required"`

	// FolderID String ID of the folder that contains the project, or `null`.
	FolderID string `json:"folder_id"`

	// IsInviteOnly Whether joining the workspace project requires an invitation.
	IsInviteOnly bool `json:"is_invite_only"`

	// IsLinkSharingEnabled Whether invitation links are enabled for the project.
	IsLinkSharingEnabled bool `json:"is_link_sharing_enabled"`

	// Status Project status.
	//
	// At the moment, this is for workspace projects only.
	Status ProjectStatus `json:"status" validate:"required"`

	// WorkspaceID String ID of the workspace that contains the project.
	WorkspaceID string `json:"workspace_id" validate:"required"`

	// IsPendingDefaultCollaboratorInvites Whether default collaborator invitations are still being created in the background.
	IsPendingDefaultCollaboratorInvites bool `json:"is_pending_default_collaborator_invites"`

	// IsProjectInsightsEnabled Whether project insights are enabled for the project.
	IsProjectInsightsEnabled bool `json:"is_project_insights_enabled"`
}

func (w WorkspaceProjectSyncView) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(w.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := typesValidator.Var(w.Color, "required"); err != nil {
		errors = errors.Append("Color", err)
	}
	if err := typesValidator.Var(w.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if err := typesValidator.Var(w.ViewStyle, "required"); err != nil {
		errors = errors.Append("ViewStyle", err)
	}
	if err := typesValidator.Var(w.Description, "required"); err != nil {
		errors = errors.Append("Description", err)
	}
	if err := typesValidator.Var(w.PublicKey, "required"); err != nil {
		errors = errors.Append("PublicKey", err)
	}
	if v, ok := any(w.Access).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Access", err)
		}
	}
	if err := typesValidator.Var(w.CollaboratorRoleDefault, "required"); err != nil {
		errors = errors.Append("CollaboratorRoleDefault", err)
	}
	if v, ok := any(w.Status).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Status", err)
		}
	}
	if err := typesValidator.Var(w.WorkspaceID, "required"); err != nil {
		errors = errors.Append("WorkspaceID", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}
