// Code generated by oapi-codegen. DO NOT EDIT.

package todoistapi

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type ItemSyncView_Duration_AnyOf_AdditionalProperties struct {
	ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf *ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf `json:"-"`
}

func (i ItemSyncView_Duration_AnyOf_AdditionalProperties) Validate() error {
	var errors runtime.ValidationErrors
	if i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf != nil {
		if v, ok := any(i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

func (i ItemSyncView_Duration_AnyOf_AdditionalProperties) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (i *ItemSyncView_Duration_AnyOf_AdditionalProperties) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf == nil {
		i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf = &ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, i.ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf); err != nil {
		return fmt.Errorf("ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf unmarshal: %w", err)
	}

	return nil
}

type AnyProjectSyncViewResponse_AnyOf struct {
	runtime.Either[PersonalProjectSyncView, WorkspaceProjectSyncView]
}

func (a *AnyProjectSyncViewResponse_AnyOf) Validate() error {
	if a.IsA() {
		if v, ok := any(a.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if a.IsB() {
		if v, ok := any(a.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf struct {
	runtime.Either[int, string]
}

func (i *ItemSyncView_Duration_AnyOf_AdditionalProperties_AnyOf) Validate() error {
	if i.IsA() {
		if v, ok := any(i.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if i.IsB() {
		if v, ok := any(i.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type ProjectAccessView_Configuration_AnyOf struct {
	union json.RawMessage
}

func (p *ProjectAccessView_Configuration_AnyOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the ProjectAccessView_Configuration_AnyOf as bytes
func (p *ProjectAccessView_Configuration_AnyOf) Raw() json.RawMessage {
	return p.union
}

// AsRestrictedProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a RestrictedProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsRestrictedProjectConfiguration() (RestrictedProjectConfiguration, error) {
	return runtime.UnmarshalAs[RestrictedProjectConfiguration](p.union)
}

// AsValidatedRestrictedProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a validated RestrictedProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsValidatedRestrictedProjectConfiguration() (RestrictedProjectConfiguration, error) {
	val, err := p.AsRestrictedProjectConfiguration()
	if err != nil {
		var zero RestrictedProjectConfiguration
		return zero, err
	}
	if err := p.validateRestrictedProjectConfiguration(val); err != nil {
		var zero RestrictedProjectConfiguration
		return zero, err
	}
	return val, nil
}

// FromRestrictedProjectConfiguration overwrites any union data inside the ProjectAccessView_Configuration_AnyOf as the provided RestrictedProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) FromRestrictedProjectConfiguration(val RestrictedProjectConfiguration) error {
	// Validate before storing
	if err := p.validateRestrictedProjectConfiguration(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsTeamProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a TeamProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsTeamProjectConfiguration() (TeamProjectConfiguration, error) {
	return runtime.UnmarshalAs[TeamProjectConfiguration](p.union)
}

// AsValidatedTeamProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a validated TeamProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsValidatedTeamProjectConfiguration() (TeamProjectConfiguration, error) {
	val, err := p.AsTeamProjectConfiguration()
	if err != nil {
		var zero TeamProjectConfiguration
		return zero, err
	}
	if err := p.validateTeamProjectConfiguration(val); err != nil {
		var zero TeamProjectConfiguration
		return zero, err
	}
	return val, nil
}

// FromTeamProjectConfiguration overwrites any union data inside the ProjectAccessView_Configuration_AnyOf as the provided TeamProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) FromTeamProjectConfiguration(val TeamProjectConfiguration) error {
	// Validate before storing
	if err := p.validateTeamProjectConfiguration(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsPublicProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a PublicProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsPublicProjectConfiguration() (PublicProjectConfiguration, error) {
	return runtime.UnmarshalAs[PublicProjectConfiguration](p.union)
}

// AsValidatedPublicProjectConfiguration returns the union data inside the ProjectAccessView_Configuration_AnyOf as a validated PublicProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) AsValidatedPublicProjectConfiguration() (PublicProjectConfiguration, error) {
	val, err := p.AsPublicProjectConfiguration()
	if err != nil {
		var zero PublicProjectConfiguration
		return zero, err
	}
	if err := p.validatePublicProjectConfiguration(val); err != nil {
		var zero PublicProjectConfiguration
		return zero, err
	}
	return val, nil
}

// FromPublicProjectConfiguration overwrites any union data inside the ProjectAccessView_Configuration_AnyOf as the provided PublicProjectConfiguration
func (p *ProjectAccessView_Configuration_AnyOf) FromPublicProjectConfiguration(val PublicProjectConfiguration) error {
	// Validate before storing
	if err := p.validatePublicProjectConfiguration(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// validateRestrictedProjectConfiguration validates a RestrictedProjectConfiguration value
func (p *ProjectAccessView_Configuration_AnyOf) validateRestrictedProjectConfiguration(val RestrictedProjectConfiguration) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTeamProjectConfiguration validates a TeamProjectConfiguration value
func (p *ProjectAccessView_Configuration_AnyOf) validateTeamProjectConfiguration(val TeamProjectConfiguration) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validatePublicProjectConfiguration validates a PublicProjectConfiguration value
func (p *ProjectAccessView_Configuration_AnyOf) validatePublicProjectConfiguration(val PublicProjectConfiguration) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (p ProjectAccessView_Configuration_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *ProjectAccessView_Configuration_AnyOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}
