package: generated
skip-prune: true
user-templates:
  typeDef: templates/type_def.tmpl
output:
  use-single-file: false
  directory: ..
generate:
  client: true
  client-with-response: true
  models: true
