# go.mod replaces github.com/deepmap/oapi-codegen with DoorDash's
# github.com/doordash-oss/oapi-codegen-dd fork.
package: generated
generate:
  client: true
  models: true
output-options:
  skip-prune: true
