package db

import (
	"context"
	"fmt"
)

// RetainFederationEvents combines admitted source events with the exact events
// generated by their transaction. Generated peer-project audit events never
// pass through a source-project rediscovery filter. Ingest holds the write
// transaction while this runs, so the remaining events are read in one call.
func RetainFederationEvents(ctx context.Context, ids []string, produced []Event, fetch func(context.Context, []string) ([]Event, error)) ([]string, []Event, error) {
	retained := make(map[string]Event, len(ids)+len(produced))
	for _, event := range produced {
		retained[event.UID] = event
	}
	seen := make(map[string]bool, len(ids)+len(produced))
	ordered := make([]string, 0, len(ids)+len(produced))
	var missing []string
	for _, id := range ids {
		if seen[id] {
			continue
		}
		seen[id] = true
		ordered = append(ordered, id)
		if _, ok := retained[id]; !ok {
			missing = append(missing, id)
		}
	}
	for _, event := range produced {
		if !seen[event.UID] {
			seen[event.UID] = true
			ordered = append(ordered, event.UID)
		}
	}
	if len(missing) > 0 {
		fetched, err := fetch(ctx, missing)
		if err != nil {
			return nil, nil, err
		}
		for _, event := range fetched {
			retained[event.UID] = event
		}
	}
	events := make([]Event, 0, len(ordered))
	for _, id := range ordered {
		event, ok := retained[id]
		if !ok {
			return nil, nil, fmt.Errorf("%w: committed federation event %s", ErrNotFound, id)
		}
		events = append(events, event)
	}
	return ordered, events, nil
}
